name = "migrant"
version = "0.2.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Database migrations for SQLite in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "migrant" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
gleam_erlang = ">= 0.24.0"
