name = "migrant"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Database migrations for SQLite in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "migrant" }
gleam = ">= 1.9.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 1.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
